# Generated by Django 4.2.5 on 2023-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
