# Generated by Django 4.2.5 on 2023-10-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/fuel_station_logos'),
        ),
    ]
