# Generated by Django 4.2.5 on 2023-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='profile_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
