# Generated by Django 4.2.5 on 2023-11-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_order_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
    ]
