# Generated by Django 4.2.5 on 2023-10-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_locationdetails_pumpdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpdetails',
            name='valueaddedservice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
