# Generated by Django 4.2.5 on 2023-11-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_order_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='cancel',
        ),
    ]
