# Generated by Django 4.2.5 on 2023-11-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancel',
            new_name='is_active',
        ),
    ]
