# Generated by Django 4.2.5 on 2023-11-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
