# Generated by Django 4.2.5 on 2023-11-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_fuel_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='addressline1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='addressline2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
