# Generated by Django 4.2.5 on 2023-11-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razor_pay_payment_signature',
        ),
    ]
