# Generated by Django 4.2.5 on 2024-01-31 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_payment_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maploaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pump_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_area_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_area_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.fuelstation')),
            ],
        ),
    ]
