# Generated by Django 4.2.5 on 2024-02-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_deliveryteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryTeam',
        ),
    ]
