# Generated by Django 4.2.5 on 2024-02-05 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_delete_deliveryteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('vehno', models.CharField(max_length=15, unique=True)),
                ('propic', models.ImageField(blank=True, null=True, upload_to='media/delivery_pic')),
                ('drivelic', models.ImageField(blank=True, null=True, upload_to='media/driving_license')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.locationdetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
