# Generated by Django 4.2.5 on 2024-02-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_deliveryteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryTeam',
        ),
    ]
