# Generated by Django 4.2.5 on 2024-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_deliveryteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
