# Generated by Django 4.2.5 on 2024-02-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_deliveryteam_is_accepted_deliveryteam_is_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryTeam',
        ),
    ]
