# Generated by Django 4.2.5 on 2024-02-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_deliveryteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maploaction',
        ),
    ]
