# Generated by Django 4.2.5 on 2024-02-06 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_delete_maploaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pump_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_area_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_area_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
