# Generated by Django 4.2.5 on 2024-02-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_maplocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLocation',
        ),
    ]
