# Generated by Django 4.2.4 on 2024-02-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_order_lat_order_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='itemprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
