# Generated by Django 4.2.4 on 2024-02-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_order_deliveryprice_order_itemprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
