# Generated by Django 4.2.4 on 2024-02-19 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_deliveryteam_latitude_deliveryteam_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.deliveryteam'),
        ),
    ]
