# Generated by Django 4.2.4 on 2024-02-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_thread_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='station',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
