# Generated by Django 4.2.4 on 2024-02-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_team',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='station',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='station',
        ),
        migrations.DeleteModel(
            name='DeliveryTeam',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
