# Generated by Django 4.2.4 on 2024-02-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_deliveryteam_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='is_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
