# Generated by Django 4.2.4 on 2024-02-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_deliveryteam_is_assigned_deliveryteam_is_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryteam',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryteam',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
