# Generated by Django 4.2.4 on 2024-02-27 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_deliveryteam_checkin_time_deliveryteam_checkout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryteam',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='deliveryteam',
            name='checkout_time',
        ),
        migrations.CreateModel(
            name='CheckInOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.deliveryteam')),
            ],
        ),
    ]
