# Generated by Django 4.2.4 on 2024-02-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0049_remove_deliveryteam_checkin_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
