# Generated by Django 4.2.5 on 2024-03-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0051_thread_chatmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
