# Generated by Django 4.2.4 on 2024-03-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_fuel_discount_fuel_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
